FROM python:3.11-slim
WORKDIR /app

COPY pyproject.toml README.md ./
COPY dashboard/ ./dashboard/
COPY app/ ./app/
COPY scripts/ ./scripts/
RUN pip install --no-cache-dir --upgrade pip &&     pip install --no-cache-dir "."

ENV PYTHONPATH=/app
EXPOSE 8501
CMD ["streamlit", "run", "dashboard/main.py", "--server.port=8501", "--server.address=0.0.0.0"]
